version: '3.8'

services:
  db:
    container_name: Postgresql_Container4
    image: postgres
    environment:
      POSTGRES_USER: kareem
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5777:5432"
    networks:
      - db
    restart: unless-stopped
  redis:
    image: "redis:alpine"
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass sOmE_sEcUrE_pAsS
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
networks:
  db:
    driver: bridge

volumes:
  db: